name: ruangpustaka
version: 1.0.0+1
publish_to: none
description: Project Aplikasi Perpustakaan Digital Berbasis Android UKK RPL 2024
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  dio: 5.4.1
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  flutter: 
    sdk: flutter

#  Library
  lottie: ^2.0.0
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.10+1
  email_validator: ^2.1.16
  awesome_snackbar_content: ^0.1.3
  font_awesome_flutter: ^10.7.0
  qr_flutter: ^4.1.0
  fluttertoast: ^8.2.4
  intl: ^0.18.1
  iconsax: ^0.0.8
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  syncfusion_flutter_pdfviewer: ^23.2.6

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/onboarding/
    - assets/gif/
    - assets/home/
    - assets/home/fitur/
    - assets/ruangpustaka/

